name: Deploy Ec2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh ec2 로그인
        uses: appleboy/ssh-action@v1.0.3
        with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: |
          cd /home/2024devSpring
          git config --global --add safe.directory /home/2024dev1/12_jpa_crud
          sudo git pull origin main
          sudo ./gradlew clean build
          sudo fuser -k -n tcp 8080 
          # nohup java -jar build/libs/*SNAPSHOT.war &
